# Generated by Django 4.2.7 on 2025-07-15 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('role', models.CharField(choices=[('athlete', 'Athlete'), ('coach', 'Coach'), ('staff', 'Staff')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_state', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=30)),
                ('budget_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('meals', 'Meals'), ('transportation', 'Transportation'), ('lodging', 'Lodging'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.CharField(max_length=200)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('incurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traveler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.traveler')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='travel.trip')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('bus', 'Bus/Van'), ('car', 'Rental Car'), ('other', 'Other')], max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('confirmation_number', models.CharField(blank=True, max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('cost_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripTraveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_diem_total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.traveler')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='travel.trip')),
            ],
            options={
                'unique_together': {('trip', 'traveler')},
            },
        ),
    ]
